config/routes.rb
Blog::Application.routes.draw do

  resources :comments

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "posts/index"
  get "users/index"

  resources :posts
  resources :sessions  
  resources :users

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :parent
  validates :title, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password_digest, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :content, :parent_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post=Post.new
    @posts = Post.all
  end
  
  def create
    Post.create post_params
    redirect_to :back
  end

  def edit
    @post = Post.find id_params 
  end

  def update
    post = Post.find id_params
    if post.update_attributes post_params
      redirect_to posts_path, :notice => 'Your task has successfully been updated'
    else
      redirect_to :back, :notice => 'There was an error updating your post.'
    end
  end

  def destroy
    Post.destroy id_params
    redirect_to :back, :notice => 'Post has been deleted.' 
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def id_params
    params.require(:id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_name(params[:user_name])
    if user && user.authenticate(params[:user_password])
      session[:user_id] = user.id
      flash.alert = "Now signed in"
      redirect_to :back
    else
      flash.alert = "Invalid email or password"
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    flash.alert = "Now signed out"
    redirect_to :back
  end
  
  def log_in_params
    params.require(:user_name)
    params.require(:user_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
    @users = User.all
  end

  def create
    User.create user_params
    redirect_to :back
  end
  
  def new
    @user = User.new
  end

  def edit
    @user = User.find id_params 
  end

  def update
    user = User.find id_params
    if user.update_attributes user_params
      redirect_to users_path, :notice => 'Your task has successfully been updated'
    else
      redirect_to :back, :notice => 'There was an error updating your post.'
    end
  end
 
  def destroy
    User.destroy id_params
    redirect_to :back, :notice => 'Post has been deleted.' 
  end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def id_params
    params.require(:id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :parent %><br>
    <%= f.text_field :parent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Parent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= comment.parent %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @comment.parent %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
<ul class="nav nav-pills container">
<li><%=link_to 'Main', posts_index_path %></li>
<li><%=link_to 'Login', log_in_path %></li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render :partial => 'layouts/navbar' %>
<% flash.each do |name, message| %>
  <%= content_tag :div, message, :id => "flash_#{name}" %>
<% end %>
  <%= yield %>

</body>
</html>

app/views/posts/_post_form.erb
<%= form_for @post do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :content %>
<%= f.text_field :content %>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
<h1>Edit</h1>
<%=render 'post_form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
<h1>Posts</h1>
<%=render 'post_form' %>
<ul>
  <% for post in @posts %>
  <li id="post_<%= post.id %>"><%= post.title %>
    | <%= link_to 'Edit', edit_post_path(post) %>
    | <%= link_to 'Delete', post, :method => 'delete' %>
  </li>
  <% end %>
</ul>
<div>

app/views/users/_user_form.erb
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<%=render 'user_form' %>
</div>

app/views/users/index.html.erb
<div class="container">
<ul>
  <% for user in @users %>
  <li id="user_<%= user.id %>"><%=user.name %> 
    | <%= link_to 'Edit', edit_user_path(user) %>
    | <%= link_to 'Delete', user, :method => 'delete' %>
  </li>
  <% end %>
</ul>
</div>

app/views/users/new.html.erb
<div class="container">

<%=render 'user_form' %>
</div>